name: CI - Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on Node ${{ matrix.node-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x, 16.x, 18.x, 20.x]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{ matrix.os }}-node-${{ matrix.node-version }}

      - name: Notify on failure
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              // Получаем информацию о PR
              const pr = context.payload.pull_request
              if (pr) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  body: `🚨 Тесты не прошли на ${process.platform} (Node ${process.version})\n` +
                         `Проверьте отчёт: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
                })
              }
            
              // Отправляем уведомление для коммитов без PR
              else {
                const commitUrl = `${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}`
                await github.repos.createCommitComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  commit_sha: "${{ github.sha }}",
                  body: `❌ Тесты не прошли!\n` +
                         `Проверьте отчёт: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n` +
                         `Ссылка на коммит: ${commitUrl}`
                })
              }
            } catch (error) {
              core.warning(`Failed to create comment: ${error.message}`)
            }

  coverage-finalize:
    name: Finalize coverage report
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Finalize Coveralls processing
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true